### ISSUE TITLE
Table indexing tests broken

### ISSUE THREAD

**Issue by duncanhobbs** [jacobadenbaum/TexTables.jl#19]
When I ran the [runtests.jl](https://github.com/jacobadenbaum/TexTables.jl/blob/master/test/runtests.jl) file, I got a message that two of the tests [here](https://github.com/jacobadenbaum/TexTables.jl/blob/master/test/indexing.jl#L123-L124) were broken (not that they failed)

I notice that the two lines above the broken are commented out. Should lines 123 and 124 be commented out as well?

**Comment by jacobadenbaum** [comment]
Yeah.  I wanted to keep them in there as a reminder to myself that I want to throw an error in those cases.  But for now, just ignore the broken test message.
