### ISSUE TITLE
Error when creating table from single column. 

### ISSUE THREAD

**Issue by Shresth-Garg** [jacobadenbaum/TexTables.jl#31]
If I have a single TableCol (say t), and use the command `to_tex(t)` it throws up an error `ERROR: MethodError: no method matching to_tex(::TableCol{1, 1})`. The command works when I use `to_tex(hcat(t,t))`. It looks like creating a table needs at least two columns. I am not sure if that is desirable as some situations call for creating a single column table.

**Comment by jacobadenbaum** [comment]
This should be fixed with the most recent patch
